/// Khoá icon của task/routine/phần thưởng, và đường dẫn asset tương ứng.
///
/// Hình vẽ từ **asset PNG** trong `assets/icons/` (Fluent Emoji, MIT) qua
/// `AppIcon`, không phải emoji của hệ thống nữa — xem `assets/icons/README.md`.
/// Map [taskIcons] vẫn giữ emoji tương ứng vì nó còn dùng được ở chỗ chỉ nhận
/// chuỗi (nhãn accessibility, log, test đối chiếu), nhưng **UI thì dùng
/// `AppIcon`**.
///
/// Khoá khớp với `iconKey` trong `TaskPreset`/`RoutinePreset`
/// (`lib/domain/entities/presets.dart`) và với **tên file** trong `assets/icons/`.
library;

/// Thư mục chứa asset icon.
const String kIconAssetDir = 'assets/icons';

/// Đường dẫn asset của một khoá icon.
///
/// Khoá lạ vẫn trả về đường dẫn (không có file), để `AppIcon` hiện dấu hỏi và in
/// cảnh báo — thà thấy một chỗ sai còn hơn im lặng vẽ ⭐ giống mọi việc khác.
String assetPathForIcon(String iconKey) => '$kIconAssetDir/$iconKey.png';

/// Emoji -> khoá asset, cho hai chỗ **đã lưu ký tự emoji vào DB**: `jars.emoji`
/// và `members.avatar_key`.
const Map<String, String> kEmojiIconKeys = {
  // Hũ — `kJarEmojis` trong `lib/domain/entities/jar_def.dart`.
  '🛍️': 'jar_spend',
  '🐷': 'jar_save',
  '💝': 'jar_give',
  '📚': 'books',
  '🎮': 'game',
  '⚽': 'soccer',
  '🎨': 'palette',
  '🎁': 'jar_gift',
  '🍦': 'ice_cream',
  '🚲': 'bike',
  '🎸': 'jar_guitar',
  '🧸': 'toy',
  '🌱': 'plant',
  '🏦': 'jar_bank',
  '✈️': 'jar_plane',
  '🎪': 'jar_circus',
  '📥': 'jar_inbox',

  // Avatar — `kAvatarEmojis` dưới đây.
  '🦁': 'av_lion',
  '🐱': 'av_cat',
  '🐶': 'av_dog',
  '🐰': 'av_rabbit',
  '🐼': 'av_panda',
  '🦊': 'av_fox',
  '🐨': 'av_koala',
  '🐯': 'av_tiger',
  '🐸': 'av_frog',
  '🦄': 'av_unicorn',
  '🐧': 'av_penguin',
  '🐵': 'av_monkey',
};

/// Khoá asset cho một emoji đã lưu trong DB.
String iconKeyForEmoji(String? emoji) =>
    kEmojiIconKeys[emoji] ?? kDefaultTaskIconKey;

const Map<String, String> taskIcons = {
  // Nhóm cơ bản
  'tooth': '🪥',
  'bed': '🛏️',
  'shirt': '👕',
  'food': '🥣',
  'backpack': '🎒',
  'pencil': '✏️',
  'book': '📖',
  'music': '🎵',
  'broom': '🧹',
  'shower': '🚿',
  'moon': '🌙',
  'hanger': '🧥',
  'dish': '🍽️',
  'table': '🪑',
  'trash': '🗑️',
  'laundry': '🧺',
  'plant': '🌱',
  'paw': '🐾',
  'toy': '🧸',
  'run': '🏃',
  'heart': '❤️',
  'eye_off': '📵',
  'sunrise': '🌅',
  'wb_cloudy': '☁️',
  'books': '📚',
  'abacus': '🧮',
  'palette': '🎨',
  'soccer': '⚽',
  'bike': '🚲',
  'park': '🏞️',
  'phone_off': '🔇',
  'clock': '⏰',
  'star': '⭐',
  'clipboard': '📋',
  'gem': '💎',
  'party': '🎉',
  'warning': '⚠️',
  'bee': '🐝',

  // 1. Việc nhà & Vệ sinh (Chores & Cleaning)
  'sponge': '🧽',
  'bucket': '🪣',
  'soap': '🧼',
  'plunger': '🪠',
  'window': '🪟',
  'door': '🚪',
  'toolbox': '🧰',
  'hammer': '🔨',
  'wrench': '🔧',
  'iron': '👞',

  // 2. Học tập & Kỹ năng (Study & Skills)
  'microscope': '🔬',
  'telescope': '🔭',
  'calendar': '📅',
  'artist_palette': '🎨',
  'paintbrush': '🖌️',
  'crayon': '🖍️',
  'fountain_pen': '🖋️',
  'notebook': '📓',
  'graduation_cap': '🎓',
  'magnifying_glass': '🔍',
  'test_tube': '🧪',
  'bookmark': '🔖',
  'ruler': '📏',
  'trophy': '🏆',
  'medal_1st': '🥇',
  'medal_2nd': '🥈',
  'medal_3rd': '🥉',
  'crown': '👑',

  // 3. Ăn uống, Vệ sinh & Sức khoẻ (Food & Health)
  'apple': '🍎',
  'banana': '🍌',
  'carrot': '🥕',
  'broccoli': '🥦',
  'milk': '🥛',
  'water_drop': '💧',
  'water_bottle': '🥤',
  'sandwich': '🥪',
  'bowl_with_spoon': '🥣',
  'fork_and_knife': '🍽️',
  'bath': '🛁',
  'bandage': '🩹',
  'pill': '💊',
  'stethoscope': '🩺',
  'sun': '☀️',
  'rainbow': '🌈',

  // 4. Thể thao & Vui chơi (Sports & Play)
  'basketball': '🏀',
  'badminton': '🏸',
  'tennis': '🎾',
  'ping_pong': '🏓',
  'volleyball': '🏐',
  'skateboard': '🛹',
  'roller_skate': '🛼',
  'kite': '🪁',
  'balloon': '🎈',
  'yo_yo': '🪀',
  'teddy_bear': '🧸',
  'bowling': '🎳',
  'guitar': '🎸',
  'violin': '🎻',
  'drum': '🥁',
  'trumpet': '🎺',
  'headphones': '🎧',
  'camera': '📷',
  'sparkles': '✨',
  'fireworks': '🎆',
  'gift': '🎁',

  // 5. Thú cưng, Cây cối & Thiên nhiên (Pets & Nature)
  'tree': '🌳',
  'seedling': '🌱',
  'blossom': '🌸',
  'sunflower': '🌻',
  'butterfly': '🦋',
  'ladybug': '🐞',
  'fish': '🐠',
  'cat_face': '🐱',
  'dog_face': '🐶',
  'rabbit_face': '🐰',
  'hamster': '🐹',
  'bird': '🐦',
  'turtle': '🐢',

  // 6. Cảm xúc & Thói quen tốt (Emotions & Habits)
  'glowing_star': '🌟',
  'shooting_star': '🌠',
  'target': '🎯',
  'alarm_clock': '⏰',
  'hourglass': '⏳',
  'light_bulb': '💡',
  'puzzle_piece': '🧩',
  'battery_full': '🔋',
  'recycle': '♻️',
  'smiling_face': '😄',
  'partying_face': '🥳',

  // Phần thưởng
  'phone': '📱',
  'money': '💰',
  'ice_cream': '🍦',
  'pizza': '🍕',
  'popcorn': '🍿',
  'game': '🎮',
  'console': '🕹️',
  'ticket': '🎫',
  'suitcase': '🧳',
  'jar_gift': '🎁',
  'jar_circus': '🎪',
  'jar_plane': '✈️',
  'jar_guitar': '🎸',
};

const String taskIconFallback = '⭐';

/// Danh mục icon để nhóm và lọc.
class IconCategoryDef {
  const IconCategoryDef({
    required this.id,
    required this.nameVi,
    required this.nameEn,
    required this.iconKey,
    required this.keys,
  });

  final String id;
  final String nameVi;
  final String nameEn;
  final String iconKey;
  final List<String> keys;
}

/// 6 Danh mục icon chuẩn hoá toàn diện cho hệ thống Bé Ong.
const List<IconCategoryDef> kIconCategories = [
  IconCategoryDef(
    id: 'chores',
    nameVi: 'Việc nhà',
    nameEn: 'Chores',
    iconKey: 'broom',
    keys: [
      'broom',
      'sponge',
      'bucket',
      'soap',
      'plunger',
      'trash',
      'laundry',
      'dish',
      'table',
      'bed',
      'hanger',
      'window',
      'door',
      'toolbox',
      'hammer',
      'wrench',
      'iron',
      'tooth',
      'shower',
    ],
  ),
  IconCategoryDef(
    id: 'study',
    nameVi: 'Học tập',
    nameEn: 'Study',
    iconKey: 'books',
    keys: [
      'book',
      'books',
      'pencil',
      'notebook',
      'abacus',
      'microscope',
      'telescope',
      'calendar',
      'artist_palette',
      'paintbrush',
      'crayon',
      'fountain_pen',
      'graduation_cap',
      'magnifying_glass',
      'test_tube',
      'bookmark',
      'ruler',
      'backpack',
      'trophy',
      'crown',
    ],
  ),
  IconCategoryDef(
    id: 'health',
    nameVi: 'Ăn uống & Sức khoẻ',
    nameEn: 'Food & Health',
    iconKey: 'apple',
    keys: [
      'apple',
      'banana',
      'carrot',
      'broccoli',
      'food',
      'milk',
      'water_drop',
      'water_bottle',
      'sandwich',
      'bowl_with_spoon',
      'fork_and_knife',
      'bath',
      'bandage',
      'pill',
      'stethoscope',
      'shirt',
      'sun',
      'moon',
    ],
  ),
  IconCategoryDef(
    id: 'sports_play',
    nameVi: 'Vui chơi & Thể thao',
    nameEn: 'Sports & Play',
    iconKey: 'soccer',
    keys: [
      'soccer',
      'basketball',
      'badminton',
      'tennis',
      'ping_pong',
      'volleyball',
      'skateboard',
      'roller_skate',
      'bike',
      'bowling',
      'kite',
      'balloon',
      'yo_yo',
      'toy',
      'teddy_bear',
      'game',
      'console',
      'park',
      'camera',
      'guitar',
      'violin',
      'drum',
      'trumpet',
      'headphones',
    ],
  ),
  IconCategoryDef(
    id: 'pets_nature',
    nameVi: 'Thú cưng & Tự nhiên',
    nameEn: 'Pets & Nature',
    iconKey: 'paw',
    keys: [
      'paw',
      'cat_face',
      'dog_face',
      'rabbit_face',
      'hamster',
      'bird',
      'turtle',
      'fish',
      'butterfly',
      'ladybug',
      'plant',
      'tree',
      'seedling',
      'blossom',
      'sunflower',
      'rainbow',
      'wb_cloudy',
      'sunrise',
    ],
  ),
  IconCategoryDef(
    id: 'habits_rewards',
    nameVi: 'Cảm xúc & Phần thưởng',
    nameEn: 'Emotions & Rewards',
    iconKey: 'heart',
    keys: [
      'heart',
      'smiling_face',
      'partying_face',
      'sparkles',
      'fireworks',
      'gift',
      'medal_1st',
      'medal_2nd',
      'medal_3rd',
      'gem',
      'party',
      'glowing_star',
      'shooting_star',
      'target',
      'alarm_clock',
      'clock',
      'hourglass',
      'light_bulb',
      'puzzle_piece',
      'battery_full',
      'recycle',
      'eye_off',
      'phone_off',
      'clipboard',
      'warning',
      'bee',
      'ice_cream',
      'pizza',
      'popcorn',
      'phone',
      'money',
      'ticket',
      'suitcase',
      'jar_gift',
      'jar_circus',
      'jar_plane',
      'jar_guitar',
    ],
  ),
];

/// Icon chọn được khi bố mẹ tự tạo **phần thưởng**.
const List<String> kRewardIconKeys = [
  'gift',
  'medal_1st',
  'medal_2nd',
  'medal_3rd',
  'trophy',
  'crown',
  'ice_cream',
  'pizza',
  'popcorn',
  'game',
  'console',
  'phone',
  'money',
  'ticket',
  'suitcase',
  'sparkles',
  'fireworks',
  'party',
  'gem',
  'balloon',
  'toy',
  'teddy_bear',
  'park',
  'soccer',
  'bike',
  'skateboard',
  'books',
  'palette',
  'guitar',
  'headphones',
  'camera',
  'heart',
  'jar_gift',
  'jar_circus',
  'jar_plane',
  'jar_guitar',
];

/// Icon mặc định của phần thưởng.
const String kDefaultRewardIconKey = 'jar_gift';

/// Icon chọn được cho **mục tiêu tiết kiệm**.
const List<String> kGoalIconKeys = [kDefaultGoalIconKey, ...kRewardIconKeys];

/// Icon mặc định của mục tiêu tiết kiệm: con heo đất.
const String kDefaultGoalIconKey = 'jar_save';

/// Icon mặc định khi tạo việc mới.
const String kDefaultTaskIconKey = 'pencil';

String iconForKey(String? iconKey) => taskIcons[iconKey] ?? taskIconFallback;

/// Danh sách toàn bộ icon hợp lệ cho nhiệm vụ (110+ icons).
const List<String> kTaskIconKeys = [
  // 1. Chores & Cleaning
  'tooth',
  'bed',
  'shirt',
  'broom',
  'sponge',
  'bucket',
  'soap',
  'plunger',
  'trash',
  'laundry',
  'dish',
  'table',
  'hanger',
  'shower',
  'window',
  'door',
  'toolbox',
  'hammer',
  'wrench',
  'iron',

  // 2. Study & Skills
  'pencil',
  'book',
  'books',
  'notebook',
  'backpack',
  'abacus',
  'microscope',
  'telescope',
  'calendar',
  'artist_palette',
  'palette',
  'paintbrush',
  'crayon',
  'fountain_pen',
  'graduation_cap',
  'magnifying_glass',
  'test_tube',
  'bookmark',
  'ruler',
  'trophy',
  'crown',

  // 3. Food & Health
  'food',
  'apple',
  'banana',
  'carrot',
  'broccoli',
  'milk',
  'water_drop',
  'water_bottle',
  'sandwich',
  'bowl_with_spoon',
  'fork_and_knife',
  'bath',
  'bandage',
  'pill',
  'stethoscope',
  'sun',
  'moon',

  // 4. Sports & Play
  'soccer',
  'basketball',
  'badminton',
  'tennis',
  'ping_pong',
  'volleyball',
  'skateboard',
  'roller_skate',
  'bike',
  'bowling',
  'kite',
  'balloon',
  'yo_yo',
  'toy',
  'teddy_bear',
  'park',
  'camera',
  'music',
  'guitar',
  'violin',
  'drum',
  'trumpet',
  'headphones',

  // 5. Pets & Nature
  'plant',
  'paw',
  'cat_face',
  'dog_face',
  'rabbit_face',
  'hamster',
  'bird',
  'turtle',
  'fish',
  'butterfly',
  'ladybug',
  'tree',
  'seedling',
  'blossom',
  'sunflower',
  'rainbow',
  'sunrise',
  'wb_cloudy',

  // 6. Habits & Rewards
  'heart',
  'smiling_face',
  'partying_face',
  'medal_1st',
  'medal_2nd',
  'medal_3rd',
  'gem',
  'party',
  'sparkles',
  'fireworks',
  'gift',
  'glowing_star',
  'shooting_star',
  'target',
  'alarm_clock',
  'clock',
  'hourglass',
  'light_bulb',
  'puzzle_piece',
  'battery_full',
  'recycle',
  'eye_off',
  'phone_off',
  'clipboard',
  'warning',
  'bee',
];

/// Avatar mặt con vật.
const List<String> kAvatarEmojis = [
  '🦁',
  '🐱',
  '🐶',
  '🐰',
  '🐼',
  '🦊',
  '🐨',
  '🐯',
  '🐸',
  '🦄',
  '🐧',
  '🐵',
];

String avatarForKey(String? avatarKey) =>
    avatarKey != null && kAvatarEmojis.contains(avatarKey)
    ? avatarKey
    : kAvatarEmojis.first;
